import { JobApproval } from "./approval-types"

export const mockJobApprovals: JobApproval[] = [
  {
    id: "JA-001",
    jobRole: "Senior Developer",
    hiringManagerName: "Rajesh Verma",
    hiringManagerEmail: "manager@tristone.com",
    department: "Engineering",
    dateCreated: "2024-01-15",
    status: "pending",
    jobDescription: "We are seeking a talented Senior Developer to join our dynamic engineering team. The ideal candidate will have extensive experience in full-stack development, with a strong focus on React, Node.js, and cloud technologies. You will be responsible for designing and implementing scalable solutions, mentoring junior developers, and collaborating with cross-functional teams to deliver high-quality software products.",
    professionalSummary: "Join Tristone Capital as a Senior Developer and help shape the future of financial technology. Work with cutting-edge technologies in a collaborative environment where innovation and excellence are valued. We offer competitive compensation, flexible work arrangements, and opportunities for professional growth.",
    requiredSkills: ["React", "Node.js", "TypeScript", "AWS", "MongoDB"],
    experienceLevel: "5-7 years",
    location: "Bangalore, India",
    employmentType: "Full-time",
    salaryRange: "₹18-25 LPA",
    createdBy: "hradmin@tristone.com",
    createdByRole: "hr_admin"
  },
  {
    id: "JA-002",
    jobRole: "Product Manager",
    hiringManagerName: "Rajesh Verma",
    hiringManagerEmail: "manager@tristone.com",
    department: "Product",
    dateCreated: "2024-01-18",
    status: "pending",
    jobDescription: "We are looking for an experienced Product Manager to lead our product strategy and execution. The role involves working closely with engineering, design, and business teams to define product roadmaps, prioritize features, and ensure successful product launches. The ideal candidate should have a strong technical background and excellent stakeholder management skills.",
    professionalSummary: "Take ownership of innovative products at Tristone Capital. Drive product vision and strategy while working with talented teams across the organization. This role offers significant impact and visibility, with opportunities to shape products used by thousands of customers.",
    requiredSkills: ["Product Strategy", "Roadmap Planning", "Stakeholder Management", "Agile", "Data Analysis"],
    experienceLevel: "4-6 years",
    location: "Mumbai, India",
    employmentType: "Full-time",
    salaryRange: "₹20-28 LPA",
    lastReminderSent: "2024-01-22",
    createdBy: "hr@tristone.com",
    createdByRole: "hr_team"
  },
  {
    id: "JA-003",
    jobRole: "UX Designer",
    hiringManagerName: "Rajesh Verma",
    hiringManagerEmail: "manager@tristone.com",
    department: "Design",
    dateCreated: "2024-01-20",
    status: "pending",
    jobDescription: "Seeking a creative UX Designer to craft exceptional user experiences for our digital products. You will conduct user research, create wireframes and prototypes, and work closely with developers to bring designs to life. The ideal candidate has a portfolio demonstrating strong design thinking and problem-solving skills.",
    professionalSummary: "Join our design team at Tristone Capital and create beautiful, intuitive experiences that delight users. Work on diverse projects with the freedom to explore innovative design solutions. We value creativity, collaboration, and user-centered design principles.",
    requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems"],
    experienceLevel: "3-5 years",
    location: "Hyderabad, India",
    employmentType: "Full-time",
    salaryRange: "₹12-18 LPA",
    createdBy: "hradmin@tristone.com",
    createdByRole: "hr_admin"
  },
  {
    id: "JA-004",
    jobRole: "Financial Analyst",
    hiringManagerName: "Rajesh Verma",
    hiringManagerEmail: "manager@tristone.com",
    department: "Finance",
    dateCreated: "2024-01-10",
    status: "approved",
    jobDescription: "Looking for a detail-oriented Financial Analyst to support our finance team with financial planning, analysis, and reporting. You will analyze financial data, prepare forecasts, and provide insights to support business decisions. Strong Excel skills and financial modeling experience required.",
    professionalSummary: "Advance your finance career at Tristone Capital, a leading financial services company. Work with complex financial data, develop analytical skills, and contribute to strategic business decisions. We offer a collaborative environment with excellent learning opportunities.",
    requiredSkills: ["Financial Modeling", "Excel", "SQL", "Data Analysis", "Forecasting"],
    experienceLevel: "2-4 years",
    location: "Delhi, India",
    employmentType: "Full-time",
    salaryRange: "₹10-15 LPA",
    approvalDate: "2024-01-12",
    createdBy: "hr@tristone.com",
    createdByRole: "hr_team"
  },
  {
    id: "JA-005",
    jobRole: "Data Scientist",
    hiringManagerName: "Rajesh Verma",
    hiringManagerEmail: "manager@tristone.com",
    department: "Data Science",
    dateCreated: "2024-01-08",
    status: "rejected",
    jobDescription: "Seeking an innovative Data Scientist to extract insights from large datasets and build predictive models. You will work on machine learning projects, analyze complex data, and collaborate with business teams to solve challenging problems. Strong programming and statistical skills required.",
    professionalSummary: "Join our data science team at Tristone Capital and work on exciting ML projects that drive business value. Leverage state-of-the-art tools and techniques while collaborating with talented data professionals. We offer opportunities to work on diverse datasets and cutting-edge ML applications.",
    requiredSkills: ["Python", "Machine Learning", "Statistics", "SQL", "TensorFlow"],
    experienceLevel: "3-5 years",
    location: "Bangalore, India",
    employmentType: "Full-time",
    salaryRange: "₹15-22 LPA",
    approvalDate: "2024-01-11",
    rejectionReason: "Budget constraints for this quarter. Will revisit in Q2.",
    createdBy: "hradmin@tristone.com",
    createdByRole: "hr_admin"
  }
]
